### ISSUE TITLE
have a ready-made onnx file?

### ISSUE THREAD

**Issue by zmoth** [wenet-e2e/wekws#159]
有现成的onnx文件吗？类似于wespeaker在huggingface上的。我使用魔搭社区上面的pt模型一直转换失败.

**Comment by mlxu995** [comment]
方便的话发一下你转 onnx 失败的 pt 的地址

**Comment by zmoth** [comment]
https://www.modelscope.cn/models/iic/speech_charctc_kws_phone-wenwen/files

使用的是run_fsmn_ctc.sh
```sh
./run_fsmn_ctc.sh 4 4
```

```sh
checkpoint=
dir=exp/speech_charctc_kws_phone-wenwen
average_model=true
num_average=10
if $average_model ;then
  score_checkpoint=$dir/finetune_avg_${num_average}.pt
else
  score_checkpoint=$dir/final.pt
fi

download_dir=./data/local # your data dir
```

其实上面的模型我都尝试过，有些是bin文件不知道怎么转换，还有的(https://www.modelscope.cn/iic/speech_charctc_kws_phone-xiaoyun)报错是
```
Traceback (most recent call last):
  File "wekws/bin/export_onnx.py", line 103, in <module>
    main()
  File "wekws/bin/export_onnx.py", line 42, in main
    feature_dim = configs['model']['input_dim']
KeyError: 'model'
```

**Comment by mlxu995** [comment]
ctc loss 的模型暂时还没有支持导出 onnx 和 c++ 推理，你可以先试试 maxpooling loss 的模型
