### ISSUE TITLE
examples/speechcommand_v1/s0  训练的ONNX模型可以转换成ort格式吗

### ISSUE THREAD

**Issue by taorui-plus** [wenet-e2e/wekws#162]
我在执行这个命令的时候
`python -m onnxruntime.tools.convert_onnx_models_to_ort avg_10.onnx`
报错：
`Traceback (most recent call last):
  File "/root/anaconda3/envs/wekws/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/wekws/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/onnxruntime/tools/convert_onnx_models_to_ort.py", line 17, in <module>
    from .onnx_model_utils import get_optimization_level
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/onnxruntime/tools/onnx_model_utils.py", line 8, in <module>
    import onnx
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/onnx/__init__.py", line 76, in <module>
    from onnx import serialization
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/onnx/serialization.py", line 16, in <module>
    import google.protobuf.json_format
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/json_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/internal/type_checkers.py", line 51, in <module>
    from google.protobuf.internal import decoder
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/internal/decoder.py", line 87, in <module>
    from google.protobuf.internal import encoder
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/internal/encoder.py", line 71, in <module>
    from google.protobuf.internal import wire_format
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/internal/wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "/root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /root/anaconda3/envs/wekws/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so)`

查了问题，网络上的解答是用这个命令检查GLIBCXX是否有3.4.29信息
`strings /root/anaconda3/envs/wekws/lib/libstdc++.so.6 | grep GLIBCXX`
查看3.4.29是存在的，
也尝试
`ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /root/anaconda3/envs/wekws/lib/libstdc++.so.6`
不知道怎么解决了。

**Comment by taorui-plus** [comment]
> 输出检查下你的 gcc 路径看看
> 
> > ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.29' not found
> 
> 这一句看着是引用的 gcc 不对

gcc在这里
```
which gcc
/usr/bin/gcc
```

**Comment by taorui-plus** [comment]
> 输出检查下你的 gcc 路径看看
> 
> > ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.29' not found
> 
> 这一句看着是引用的 gcc 不对

gcc --version
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
有什么问题吗

**Comment by taorui-plus** [comment]
> 输出检查下你的路径看看，echo $PATH echo $LD_LIBRARY_PATH @taorui-plus
> 
> > ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.29' not found
> 
> 这一句看着是引用的 gcc 不对

感谢大佬，问题解决了，生成ort文件了
