### ISSUE TITLE
MDTC causal config missing and cause failed

### ISSUE THREAD

**Issue by sugarcase** [wenet-e2e/wekws#66]
![image](https://user-images.githubusercontent.com/23147096/162878736-3676b403-2b20-4b66-b4f9-bcb26f82b2b5.png)

Traceback (most recent call last):
  File "kws/bin/train.py", line 230, in <module>
    main()
  File "kws/bin/train.py", line 141, in main
    model = init_model(configs['model'])
  File "/home/pengteng.spt/wekws-master/kws/model/kws_model.py", line 125, in init_model
    causal = configs['backbone']['causal']
KeyError: 'causal'
Traceback (most recent call last):
  File "kws/bin/train.py", line 230, in <module>
    main()
  File "kws/bin/train.py", line 141, in main
    model = init_model(configs['model'])
  File "/home/pengteng.spt/wekws-master/kws/model/kws_model.py", line 125, in init_model
    causal = configs['backbone']['causal']
KeyError: 'causal'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 101738) of binary: /home/pengteng.spt/miniconda2/envs/wenet/bin/python

**Comment by mlxu995** [comment]
you can add "causal: True" (or False) in the config file  like this:
![image](https://user-images.githubusercontent.com/32296227/163715899-2e71d8ac-816c-4135-b434-a72c13d2f6a9.png)

**Comment by sugarcase** [comment]
mlxu thank you! this works, and i think it should be committed.

**Comment by mlxu995** [comment]
fixed, please see https://github.com/wenet-e2e/wekws/pull/105.
